version: '3'

services:
  todotests:
    # image: mjgargani/puppeteer:trybe1.0
    build: ./todo-app/tests
    environment:
      - FRONT_HOST=todofront  
    depends_on:
      - "todofront"
      - "todoback"      

  todoback:
    # image: node:14-alpine
    build: ./todo-app/back-end
    ports:
      - "3001:3001"

  todofront:
    # image: node:14-alpine
    build: ./todo-app/front-end
    environment:
      - REACT_APP_API_HOST=todoback
      - TZ=America/Sao_Paulo # time zone  
    depends_on:
      - "todoback"
    ports:
      - "3000:3000"
